# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SimpleApp' do
  use_frameworks!
  pod "MMDrawerController"
  pod "SnapKit"
  pod "Kingfisher"
end
